export const siteConfig = {
  company: {
    name: "VM Software Solutions",
    tagline: "Enterprise Software Solutions That Scale",
    heroBadge: "Award-Winning Software Studio",
    description: "We craft cutting-edge software solutions that drive digital transformation, optimize operations, and accelerate business growth for enterprises worldwide.",
    shortDescription: "We transform businesses with cutting-edge software solutions, delivering innovation and excellence.",
    founded: "2018",
    headquarters: "San Francisco, CA",
    email: "contact@vmsolutions.com",
    phone: "+1 (555) 123-4567",
    phoneHours: "Mon–Fri, 9am–6pm",
    emailResponse: "within 24 hours",
  },
  contactMethods: [
    {
      icon: "Mail",
      label: "Email",
      value: "contact@vmsolutions.com",
      sub: "We respond within 24 hours",
      href: "mailto:contact@vmsolutions.com",
      external: false,
    },
    {
      icon: "Phone",
      label: "Call Us",
      value: "+1 (555) 123-4567",
      sub: "Mon–Fri, 9am–6pm",
      href: "tel:+15551234567",
      external: false,
    },
    {
      icon: "MessageCircle",
      label: "WhatsApp",
      value: "+1 (555) 123-4567",
      sub: "Chat with us anytime",
      href: "https://wa.me/15551234567",
      external: true,
    },
    {
      icon: "MapPin",
      label: "Our Office",
      value: "San Francisco, CA",
      sub: "Visit our headquarters",
      href: "https://maps.google.com/?q=VM+Software+Solutions,+San+Francisco,+CA",
      external: true,
    },
  ],
  mission: "To deliver innovative, reliable, and scalable software solutions that empower businesses to thrive in the digital age.",
  vision: "To be the most trusted technology partner for businesses worldwide, driving digital transformation through cutting-edge solutions.",
  stats: [
    { value: "150+", label: "Projects Delivered" },
    { value: "40+", label: "Team Members" },
    { value: "99.7%", label: "Client Satisfaction" },
    { value: "12", label: "Industry Awards" },
  ],
  trustedBy: ["Google", "Microsoft", "Amazon", "IBM", "Samsung", "Intel"],
  nav: [
    { label: "Home", href: "#home" },
    { label: "Services", href: "#services" },
    { label: "Portfolio", href: "#portfolio" },
    { label: "About", href: "#about" },
    { label: "Contact", href: "#contact" },
  ],
  services: [
    { title: "Custom Software Development", description: "Tailored solutions built from scratch to meet your unique business requirements and challenges.", icon: "Code2" },
    { title: "Cloud Solutions", description: "Scalable cloud infrastructure and migration services for modern business needs.", icon: "Cloud" },
    { title: "Mobile Applications", description: "Native and cross-platform mobile apps that deliver exceptional user experiences.", icon: "Smartphone" },
    { title: "Enterprise Systems", description: "Comprehensive ERP, CRM, and business intelligence solutions.", icon: "Building2" },
    { title: "Cyber Security", description: "End-to-end security solutions to protect your digital assets and data.", icon: "Shield" },
    { title: "AI & ML Solutions", description: "Intelligent automation and predictive analytics powered by artificial intelligence.", icon: "Brain" },
  ],
  portfolio: [
    {
      title: "Enterprise ERP System",
      category: "Enterprise Software",
      description: "A comprehensive enterprise resource planning system with real-time analytics, inventory management, and workflow automation for manufacturing industries.",
      tech: ["React", "Node.js", "PostgreSQL", "AWS", "Redis", "Docker"],
      stats: ["50+ clients", "40% efficiency gain", "98% satisfaction"],
    },
    {
      title: "Healthcare Platform",
      category: "Healthcare Tech",
      description: "Telemedicine platform with video consultations, patient management, and AI-powered diagnostics connecting patients with healthcare providers.",
      tech: ["React Native", "Python", "Firebase", "Twilio", "TensorFlow", "WebRTC"],
      stats: ["100K+ users", "1M+ consultations", "95% accuracy"],
    },
    {
      title: "FinTech Dashboard",
      category: "Financial Technology",
      description: "Real-time financial analytics dashboard with AI-powered trading insights, portfolio management, and risk assessment tools.",
      tech: ["Vue.js", "Go", "Redis", "Docker", "WebSocket", "D3.js"],
      stats: ["1B+ transactions", "<10ms latency", "99.9% accuracy"],
    },
    {
      title: "E-commerce Platform",
      category: "Retail Tech",
      description: "Scalable e-commerce solution with AI recommendations, real-time inventory, and seamless payment integration.",
      tech: ["Next.js", "NestJS", "MongoDB", "Kubernetes", "Stripe", "ElasticSearch"],
      stats: ["35% conversion lift", "$50M+ revenue", "500K+ users"],
    },
  ],
  values: [
    { title: "Innovation", description: "Pushing boundaries with creative solutions" },
    { title: "Excellence", description: "Delivering superior quality in everything" },
    { title: "Integrity", description: "Building trust through transparency" },
    { title: "Collaboration", description: "Working together for shared success" },
  ],
  specialties: ["Enterprise Software", "Cloud Solutions", "Cybersecurity", "DevOps", "AI Integration", "Digital Transformation"],
  team: [
    {
      name: "Michael Chen",
      role: "CEO & Lead Architect",
      bio: "15+ years of enterprise software experience managing engineering teams at Fortune 500 companies.",
      education: "M.S. Computer Science, Stanford University",
      expertise: ["Cloud Architecture", "Enterprise Solutions", "Team Leadership"],
      initials: "MC",
    },
    {
      name: "Sarah Johnson",
      role: "CTO & Security Director",
      bio: "Cybersecurity expert who authored multiple papers on data privacy and holds 8 security certifications.",
      education: "Ph.D. Cybersecurity, MIT",
      expertise: ["Cybersecurity", "Data Privacy", "Risk Management"],
      initials: "SJ",
    },
    {
      name: "David Rodriguez",
      role: "VP of Engineering",
      bio: "Led transformation of organizations toward continuous delivery using DevOps and agile methodologies.",
      education: "B.S. Software Engineering, Carnegie Mellon",
      expertise: ["DevOps", "Agile Methodologies", "CI/CD"],
      initials: "DR",
    },
    {
      name: "Priya Sharma",
      role: "VP of Product & Strategy",
      bio: "Combines technical expertise with business acumen, having worked as both developer and product manager.",
      education: "MBA & M.S. Computer Science, Harvard University",
      expertise: ["Product Strategy", "Business Development", "Market Analysis"],
      initials: "PS",
    },
  ],
  social: [
    { label: "LinkedIn", href: "#", icon: "Linkedin" },
    { label: "Twitter", href: "#", icon: "Twitter" },
    { label: "GitHub", href: "#", icon: "Github" },
    { label: "Dribbble", href: "#", icon: "Dribbble" },
  ],
  footerLinks: {
    quick: [
      { label: "Home", href: "#home" },
      { label: "Services", href: "#services" },
      { label: "Portfolio", href: "#portfolio" },
      { label: "About", href: "#about" },
      { label: "Contact", href: "#contact" },
    ],
    services: ["Custom Development", "Cloud Solutions", "Mobile Apps", "Enterprise Systems", "Cyber Security", "AI & ML"],
    legal: [
      { label: "Privacy Policy", href: "#" },
      { label: "Terms of Service", href: "#" },
      { label: "Cookie Policy", href: "#" },
    ],
  },
};
